---
- name: CONFIGURING DOMAIN CONTROLLER
  hosts: DC
  gather_facts: no
  tasks:
    - name: Rename server
      custom_modules.win_hostname:
        name: "{{ inventory_hostname }}"
      register: rename

    - name: Reboot after rename
      custom_modules.win_reboot:
      when: rename.reboot_required

    - name: Install Active Directory and DNS Server Role
      custom_modules.win_feature:
        name:
          - AD-Domain-Services
          - DNS
        include_management_tools: yes
        include_sub_features: yes
        state: present
      register: result

    - name: Change Administrator password
      custom_modules.win_user:
        name: Administrator
        password: "{{ domain_admin_password }}"

    - name: Create domain
      custom_modules.win_domain:
        dns_domain_name: "{{ domain_name }}"
        domain_netbios_name: "{{ domain_short }}"
        safe_mode_password: "{{ safe_mode_pass }}"
        reboot: true

    - name: Set internal DNS server
      custom_modules.win_dns_client:
        adapter_names: '*'
        ipv4_addresses:
        - '127.0.0.1'

    - name: Configure DNS forwarders
      custom_modules.win_powershell:
        script: |
          Set-DNSServerForwarder -IPAddress {{ dns_forwarders }}

    - name: Allow RDP to specific users
      custom_modules.win_user_right:
        name: SeRemoteInteractiveLogonRight
        users:
        - Administrators

    - name: Add user accounts with misconfigurations
      custom_modules.win_user:
        name: '{{ first_user }}'
        firstname: Test
        surname: Thandelete
        password: '{{ first_user_password }}'
        state: present
        domain_username: Administrator
        domain_password: '{{ domain_admin_password }}'
        groups:
          set:
          - Domain Users
          - Remote Desktop Users
