---
- name: CONFIGURING WORKSTATION 1
  hosts: WS1
  gather_facts: no
  tasks:
    - name: Rename server
      win_hostname:
        name: "{{ inventory_hostname }}"
      register: rename

    - name: Reboot after rename
      win_reboot:
      when: rename.reboot_required

    - name: Set DNS to Domain Controller
      win_dns_client:
        adapter_names: '*'
        dns_servers:
        - "{{ hostvars['DC']['ansible_host'] }}"

    - name: Join Domain
      community.windows.win_domain_membership:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: Administrator@{{ domain_name }}
        domain_admin_password: "{{ domain_admin_password }}"
        state: domain
        reboot: true

    - name: Set autologon for specific user
      community.windows.win_auto_logon:
        username: '{{ server_admin_login }}'
        password: '{{ server_admin_password }}'

    - name: Allow RDP to specific users
      win_user_right:
        name: SeRemoteInteractiveLogonRight
        users:
        - Administrators
        - Remote Desktop Users

    - name: Map shared folder
      community.windows.win_mapped_drive:
        letter: 'Z'
        path: \\fs.{{ domain_name }}\SharedFolder
        state: present

    - name: Add user to RDP group
      win_group_membership:
        name: Remote Desktop Users
        members:
          - '{{ first_user_login }}'
        state: present

    - name: Compile a dummy binary
      local_action:
        module: shell
        args:
          cmd: mcs -reference:System.ServiceProcess.dll -out:itman.exe itman.cs
          chdir: files/
          executable: /bin/bash
      vars:
        ansible_shell_type: sh

    - name: Create directory structure prerequisite
      win_file:
        path: C:\Program Files\Remoting\Service Binary
        state: directory

    - name: Move a dummy binary
      win_copy:
        src: itman.exe
        dest: C:\Program Files\Remoting\Service Binary\itman.exe
        force: yes

    - name: Add Unquoted Service Path
      win_service:
        name: ItManSvc
        path: C:\Program Files\Remoting\Service Binary\itman.exe
        display_name: ItManSvc
        description: Internal Management Service for Administrative Tasks
        start_mode: auto
        failure_actions:
        - type: restart 
          delay_ms: 60000
        - type: none

    - name: Set service permissions
      win_shell: sc.exe sdset ItManSvc 'D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)(A;;RPWPCR;;;WD)'

    - name: Add write permissions for Authenticated Users
      win_acl:
        path: C:\Program Files\Remoting
        rights: WriteData
        state: present
        type: allow
        user: Authenticated Users
