proxmox_url             = "https://192.168.10.20:8006/api2/json"
proxmox_username        = "infra_as_code@pve"
proxmox_password        = "P@ssw0rd"
proxmox_node            = "pve"
proxmox_pool            = "Templates"
proxmox_vm_storage      = "local-zfs"
dc_template             = "WinServer2019-cloudinit"
dc_ip                   = "192.168.10.200"
