# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.
variable "proxmox_password" {
  type = string
}

variable "proxmox_template_name" {
  type    = string
  default = "ubuntu-22.04"
}

variable "proxmox_username" {
  type = string
}

variable "proxmox_vm_id" {
  type    = string
  default = "200"
}

variable "ubuntu_iso_file" {
  type    = string
  default = "ubuntu-22.04-live-server-amd64.iso"
}

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "proxmox" "autogenerated_1" {
  boot_command = ["c", "linux /casper/vmlinuz --- autoinstall ds='nocloud-net;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/' ", "<enter><wait>", "initrd /casper/initrd<enter><wait>", "boot<enter>"]
  boot_wait    = "5s"
  disks {
    disk_size         = "20G"
    storage_pool      = "local-lvm"
    storage_pool_type = "lvm"
    type              = "scsi"
  }
  http_directory = "http"
  iso_file       = "local:iso/${var.ubuntu_iso_file}"
  memory         = 1024
  network_adapters {
    bridge = "vmbr0"
  }
  node          = "proxmox"
  password      = "${var.proxmox_password}"
  proxmox_url   = "https://proxmox.madalynn.xyz/api2/json"
  ssh_password  = "madalynn"
  ssh_timeout   = "20m"
  ssh_username  = "madalynn"
  template_name = "${var.proxmox_template_name}"
  unmount_iso   = true
  username      = "${var.proxmox_username}"
  vm_id         = "${var.proxmox_vm_id}"
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.proxmox.autogenerated_1"]

  provisioner "shell" {
    inline = ["while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 1; done"]
  }

}
