ssh_password         = "P@ssw0rd" #new
ssh_username         = "root" #new
vm_name              = "Linux"
template_description = "discription"   
iso_file              = "local:iso/ubuntu-22.04-live-server-amd64.iso"
vm_cpu_cores          = "2"
vm_memory             = "4096"
vm_disk_size          = "80G"
vm_sockets            = "1"
vm_disk_format        = "raw"
