- name: Deploy Windows 10 PCs
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create Windows 10 VMs in Proxmox
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: "{{ proxmox_host }}"
        node: "{{ proxmox_node }}"
        vmid: "{{ item }}"
        name: "pc{{ item }}"
        pool: "windows_vms"
        clone: "{{ win10_template }}"
        full_clone: yes
        state: present
        timeout: 600
      loop: "{{ range(1, 11) | list }}"

    - name: Start Windows 10 VMs
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: "{{ proxmox_host }}"
        node: "{{ proxmox_node }}"
        vmid: "{{ item }}"
        state: started
      loop: "{{ range(1, 11) | list }}"

- name: Configure Windows 10 PCs
  hosts: win10
  tasks:
    - name: Set static IP
      win_shell: |
        New-NetIPAddress -InterfaceAlias "Ethernet0" -IPAddress {{ ansible_host }} -PrefixLength 24 -DefaultGateway 192.168.1.1
        Set-DnsClientServerAddress -InterfaceAlias "Ethernet0" -ServerAddresses ("192.168.1.10")

    - name: Join domain
      win_domain_membership:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "Administrator"
        domain_admin_password: "{{ domain_admin_password }}"
        state: domain
        reboot: yes
