ssh_password         = "ubuntu" #new
ssh_username         = "hhoyos" #new
vm_name              = "Ubuntu-22-04-cloudinit"
template_description = "discription"   
iso_file              = "local:iso/ubuntu-22.iso"
vm_cpu_cores          = "4"
vm_memory             = "5000"
vm_disk_size          = "100G"
vm_sockets            = "1"
vm_disk_format        = "raw"
